apiVersion: v0.0.1 #api版本号
kind: oneRuntime #只在一个runtime上运行
trigger:
  cron: "* * * * * *"
executer:
  lambda:
    func:
    - name: main.hello
    - name: main.newYear
      args: |
        {"Name":"g", "Age":1}
